version: "3.3"
services:
  backend:
    build:
      context: backend
    environment:
      - DB_HOST=postgres
    ports:
      - "3000:3000"
    depends_on:
      - "postgres"

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=maxxidata
      - POSTGRES_PASSWORD=maxxidata
    volumes:
      - ./postgres-data:/var/lib/postgresql/data